deploy_version: 0.1.22
image_tag: latest

applications:
  - name: django-asgi
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["/usr/local/bin/asgi-run"]
    replicas: 4
    ingress:
      hosts:
        - host: ohq.io
          paths: ["/api/ws"]
    extraEnv:
      - name: DOMAIN
        value: ohq.io
      - name: DJANGO_SETTINGS_MODULE
        value: officehoursqueue.settings.production
      - name: REDIS_URL
        value: redis://office-hours-queue-redis:6379
  - name: django-wsgi
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    replicas: 8
    ingress:
      hosts:
        - host: ohq.io
          paths: ["/api", "/admin", "/assets"]
    extraEnv:
      - name: DOMAIN
        value: ohq.io
      - name: DJANGO_SETTINGS_MODULE
        value: officehoursqueue.settings.production
      - name: REDIS_URL
        value: redis://office-hours-queue-redis:6379
  - name: react
    image: pennlabs/office-hours-queue-frontend
    replicas: 2
    ingress:
      hosts:
        - host: ohq.io
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
      - name: DOMAIN
        value: ohq.io
  - name: redis
    image: redis
    tag: "6.0"
    port: 6379
  - name: celery
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["celery","-A", "officehoursqueue", "worker", "-lINFO"]
    extraEnv:
      - name: DJANGO_SETTINGS_MODULE
        value: officehoursqueue.settings.production
      - name: REDIS_URL
        value: redis://office-hours-queue-redis:6379

cronjobs:
  - name: calculate-waits
    schedule: "*/5 * * * *"
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["python", "manage.py", "calculatewaittimes"]
  - name: queue-weekly-stat
    schedule: "0 8 * * *"
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["python", "manage.py", "queue_weekly_stat"]
  - name: queue-heatmap-stat
    schedule: "0 8 * * *"
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["python", "manage.py", "queue_heatmap_stat"]
  - name: calculate-wait-time-days
    schedule: "0 8 * * *"
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["python", "manage.py", "wait_time_days"]
    - name: calculate-course-stat
    schedule: "0 8 * * *"
    image: pennlabs/office-hours-queue-backend
    secret: office-hours-queue
    cmd: ["python", "manage.py", "course_stat.py"]
